import Image from "next/image";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Grid } from "@mui/joy";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Grid py={15} px={40}>
                    <Grid xs={12} mb={10} display="flex" justifyContent="center">
                        <Image src="/logo.jpg" alt="Next.js Logo" width={231} height={102} priority />
                    </Grid>
                    {children}
                </Grid>
            </body>
        </html>
    );
}

